/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
class App {
    String getGreeting() {
        return 'Hello Jenkins friends'
    }

    static void main(String[] args) {
        println new App().greeting
    }

    void CrApNaMe(def a, def b, def c, def d, def e, def f, def g, def h){
        if (false)         {
            def SOMEUNUSEDVAr


        }
    }

}
