/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
class App {
    String getGreeting() {
        return 'Hello Jenkins friends'
    }

    static void main(String[] args) {
        println new App().greeting
    }

    void CrApNaMe(){
        if (false) {
            def someunusedvar;
        }
    }

}
